'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations
Imports System.ComponentModel.DataAnnotations.Schema

Partial Public Class AspNetUserClaims
    <Key>
    <column(Order:=0)>
    Public Property Id As Integer
    Public Property ClaimType As String
    Public Property ClaimValue As String

    Public Overridable Property AspNetUsers As AspNetUsers

End Class
